apiVersion : apps/v1
kind: Deployment
metadata:
  name: mmbabuspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmbabuspringbootapp
  template:
    metadata:
      labels:
        app: mmbabuspringbootapp 
    spec:
      containers:
        - name: mmbabuspringbootapp 
          image: myacrrepo431.azurecr.io/mmbabuspringbootapp
          ports:
          - containerPort: 80
