apiVersion : apps/v1
kind: Deployment
metadata:
  name: ramspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramspringbootapp
  template:
    metadata:
      labels:
        app: ramspringbootapp 
    spec:
      containers:
        - name: ramspringbootapp 
          image: myacrrepo431.azurecr.io/ramspringbootapp
          ports:
          - containerPort: 80
